// nuxt-app/components/Project.vue
<template>
  <div>
    <a :href="url" target="_blank">
      <div
        class="
          bg-[#282828]
          p-4
          sm:w-96
          w-64
          h-min
          mx-auto
          rounded-xl
          transition-all
          ease-out
          hover:-translate-y-1
          cursor-pointer
        "
      >
        <div class="flex">
          <img :src="img" :alt="name" class="h-12 rounded-full" />
          <div
            class="my-auto pl-2 font-extrabold text-xl tracking-wide"
            :class="text_gradient"
          >
            {{ name }}
          </div>
        </div>
        <div class="max-w-xs pt-4 font-medium text-md">
          {{ description }}
        </div>
      </div>
    </a>
  </div>
</template>

<script>
export default {
  props: {
    img: String,
    name: String,
    description: String,
    text_gradient: String,
    url: String,
  },
};
</script>

// components/Project.tsx
export default function Project({
  title,
  description,
  className,
}: {
  title: string;
  description: string;
  className?: string;
}) {
  return (
    <div
      className={`${className} border-2 rounded-lg transition-all hover:-translate-y-1 duration-500 cursor-pointer max-w-72 border-[#202020] p-4 `}
    >
      <p className="text-3xl font-bold mb-2">{title}</p>
      <div className="text-gray-400">{description}</div>
    </div>
  );
}
